<template>
  <main>
    <h2>Privacy</h2>
    <p>
      This website uses Google Analytics, a web analytics service provided by
      Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files
      placed on your computer, to help the website analyze how users use the site.
      The information generated by the cookie about your use of the website will be
      transmitted to and stored by Google on servers in the United States. Your IP
      address will be truncated within the area of Member States of the European Union
      or other parties to the Agreement on the European Economic Area. Only in
      exceptional cases the whole IP address will be first transfered to a Google
      server in the USA and truncated there.
    </p>
    <p>
      Google will use this information on behalf of the operator of this website for
      the purpose of evaluating your use of the website, compiling reports on website
      activity for website operators and providing them other services relating to
      website activity and internet usage. The IP-address, that your Browser conveys
      within the scope of Google Analytics, will not be associated with any other
      data held by Google. You may refuse the use of cookies by selecting the
      appropriate settings on your browser, however please note that if you do this
      you may not be able to use the full functionality of this website.
    </p>
    <p>
      You can also opt-out from being tracked by Google Analytics with effect for the
      future by downloading and installing Google Analytics Opt-out Browser Addon for
      your current web browser: http://tools.google.com/dlpage/gaoptout?hl=en
    </p>
  </main>
</template>

<script>
export default {
  name: 'imprint',
};
</script>


